%YAML:1.0
# Limits for crossings. Anything beyond these values will be ignored.
# Note: Negative values deactivate a sensor entirely.
# Note: In the code, we use -1.0 as the default value everywhere.
#   This means that every sensor not specified here will be deactivated.

# Normal DRIVING state:
LIMIT_FOR_DRIVING_FRONTLEFT: 0.1
LIMIT_FOR_DRIVING_FRONTCENTERLEFT: 0.4
LIMIT_FOR_DRIVING_FRONTCENTER: 1.0
LIMIT_FOR_DRIVING_FRONTCENTERRIGHT: 0.4
LIMIT_FOR_DRIVING_FRONTRIGHT: 0.1
LIMIT_FOR_DRIVING_SIDELEFT: -1.0
LIMIT_FOR_DRIVING_SIDERIGHT: -1.0
LIMIT_FOR_DRIVING_REARLEFT: -1.0
LIMIT_FOR_DRIVING_REARCENTER: -1.0
LIMIT_FOR_DRIVING_REARRIGHT: -1.0
 
# CROSSING: Activated when we're standing at a crossing:
LIMIT_FOR_CROSSING_FRONTLEFT: 0.3
LIMIT_FOR_CROSSING_FRONTCENTERLEFT: 0.3
LIMIT_FOR_CROSSING_FRONTCENTER: 1.5
LIMIT_FOR_CROSSING_FRONTCENTERRIGHT: 1.05
LIMIT_FOR_CROSSING_FRONTRIGHT: 1.4

# SEARCH PARKING state:
LIMIT_FOR_SEARCH_PARKING_FRONTLEFT: -1.0
LIMIT_FOR_SEARCH_PARKING_FRONTCENTERLEFT: -1.0
LIMIT_FOR_SEARCH_PARKING_FRONTCENTER: -1.0
LIMIT_FOR_SEARCH_PARKING_FRONTCENTERRIGHT: -1.0
LIMIT_FOR_SEARCH_PARKING_FRONTRIGHT: -1.0
LIMIT_FOR_SEARCH_PARKING_SIDELEFT: -1.0
LIMIT_FOR_SEARCH_PARKING_SIDERIGHT: -1.0
LIMIT_FOR_SEARCH_PARKING_REARLEFT: -1.0
LIMIT_FOR_SEARCH_PARKING_REARCENTER: -1.0
LIMIT_FOR_SEARCH_PARKING_REARRIGHT: -1.0

# OVERTAKING state:
LIMIT_FOR_OVERTAKING_FRONTLEFT: 0.3
LIMIT_FOR_OVERTAKING_FRONTCENTERLEFT: 0.3
LIMIT_FOR_OVERTAKING_FRONTCENTER: 0.5
LIMIT_FOR_OVERTAKING_FRONTCENTERRIGHT: 1.0
LIMIT_FOR_OVERTAKING_FRONTRIGHT: 0.5
LIMIT_FOR_OVERTAKING_SIDELEFT: 0.1
LIMIT_FOR_OVERTAKING_SIDERIGHT: 0.5
LIMIT_FOR_OVERTAKING_REARLEFT: 0.1
LIMIT_FOR_OVERTAKING_REARCENTER: 0.2
LIMIT_FOR_OVERTAKING_REARRIGHT: 0.1

